name: Auto Report

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install chromium-browser
    - name: Report
      env:
        user_id: ${{ secrets.USER_ID }}
        password: ${{ secrets.PASSWORD }}
      run: "python -u main.py"
    - name: Report
      env:
        user_id: ${{ secrets.USER_ID2 }}
        password: ${{ secrets.PASSWORD2 }}
      run: "python -u main.py"
    - name: Report
      env:
        user_id: ${{ secrets.USER_ID3 }}
        password: ${{ secrets.PASSWORD3 }}
      run: "python -u main.py"
